#ifndef EDDP_HAL_PNIP_VAL_H              /* ----- reinclude-protection ----- */
#define EDDP_HAL_PNIP_VAL_H
#ifdef __cplusplus                       /* If C++ - compiler: Use C linkage */
extern "C"
{
#endif

/*****************************************************************************/
/*  Copyright (C) 2020 Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: EDDP (EthernetDeviceDriver for PN-IP)     :C&  */
/*                                                                           */
/*  F i l e               &F: eddp_hal_pnip_val.h                       :F&  */
/*                                                                           */
/*  V e r s i o n         &V: BC_PNRUN_P07.02.00.00_00.02.00.20         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: 2020-09-21                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  D e s c r i p t i o n:                                                   */
/*                                                                           */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  H i s t o r y :                                                          */
/*  ________________________________________________________________________ */
/*                                                                           */
/*  Date        Who   What                                                   */
#ifdef EDDP_MESSAGE
/*  17.06.09    AB    initial version                                        */
#endif
/*****************************************************************************/


// ---------- FILTER-------------------------------
//PNIP_REG_APIFILTERCOMMAND_IF_CONTROL                               0x00079000
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE       0x00000000
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE        0x00000001

#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_IF_SELECT_IFA             0x00000000

#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                0x00000000
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_F_CODE_STOP_FILTER        0x00000001
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_F_CODE_CHANGE_FILTER_CB   0x00000002
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_F_CODE_ENABLE_STRING_DES  0x00000003
#define PNIP_REG_APIFILTERCOMMAND_IF_CONTROL__VAL_F_CODE_CHANGE_STRING_DES  0x00000004

// ---------- RcvDMACW ----------------------------
// -

// ---------- SndDMACW ----------------------------
// -

// ---------- CPM ---------------------------------
//PNIP_REG_CPMCOMMAND_IF_CONTROL                                     0x0007D000
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE             0x00000000
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE              0x00000001

#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_IF_SELECT_IFA                   0x00000000

#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                      0x00000000
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_CPM_ON_OFF               0x00000001
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_ON_OFF               0x00000002
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_IN_OUT               0x00000003
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_SETTOUNKNOWN         0x00000004
#define PNIP_REG_CPMCOMMAND_IF_CONTROL__VAL_F_CODE_EXCHANGE_BUFFER          0x00000005
 
#define PNIP_R3_REG_CPM_PORTCONTROL__ENABLE_PORT_1                          0x00000001
#define PNIP_R3_REG_CPM_PORTCONTROL__ENABLE_PORT_2                          0x00000002
#define PNIP_R3_REG_CPM_PORTCONTROL__ENABLE_PORT_3                          0x00000004
#define PNIP_R3_REG_CPM_PORTCONTROL__ENABLE_PORT_4                          0x00000008
    
#define PNIP_R3_REG_CPM_ACW_FID_REDUNDANT_SHFT_LOW                          0
#define PNIP_R3_REG_CPM_ACW_FID_REDUNDANT_MSK_LOW                           0x0000FFFF
#define PNIP_R3_REG_CPM_ACW_FID_REDUNDANT_SHFT_HIGH                         16
#define PNIP_R3_REG_CPM_ACW_FID_REDUNDANT_MSK_HIGH                          0xFFFF0000

// ---------- PPM ---------------------------------
//PNIP_REG_PPMCOMMAND_IF_CONTROL                                     0x0007C000
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE             0x00000000
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE              0x00000001

#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_IF_SELECT_IFA                   0x00000000

#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                      0x00000000
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_PPM_ON_OFF               0x00000001
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_ON_OFF               0x00000002
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_IN_OUT               0x00000003
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_ACW_MOVE                 0x00000004
#define PNIP_REG_PPMCOMMAND_IF_CONTROL__VAL_F_CODE_EXCHANGE_BUFFER          0x00000005

#ifdef EDDP_CRT_SUPPORT_RT_OVER_UDP_ON
// ---------- RTOverUDP IPV4/6 --------------------
// PNIP_R3_REG_RTOVERUDP_APITYPE
#define PNIP_R3_REG_RTOVERUDP_ENABLE_IPV4                                   0x00000001
#define PNIP_R3_REG_RTOVERUDP_DISABLE_IPV4                                  0x00000000
#define PNIP_R3_REG_RTOVERUDP_ENABLE_IPV6                                   0x00000001
#define PNIP_R3_REG_RTOVERUDP_DISABLE_IPV6                                  0x00000000
#endif
    
// ---------- Pack --------------------------------
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE            0x00000000
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE             0x00000001
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_PACKGRP_OUT                    0x00000000
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_PACKGRP_IN                     0x00000001

#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                      0x00000000
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_F_CODE_DISABLE_GRP              0x00000001
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_F_CODE_ENABLE_GRP               0x00000002
#define PNIP_REG_PACKCOMMAND_IF_CONTROL__VAL_F_CODE_DIS_ENA_GRP              0x00000003

// ---------- FDB ---------------------------------
//PNIP_REG_FDBCOMMAND_IF_CONTROL                                     0x00014000
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE             0x00000000
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE              0x00000001

#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_IF_SELECT_IFA                   0x00000000

#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                      0x00000000
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_CLEAR_UC_TABLE           0x00000001
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_CLEAR_UC_ENTRY           0x00000002
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_INSERT_UC_ENTRY          0x00000003
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_SEARCH_MAC_ADDRESS       0x00000004
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_CHANGE_MC_ENTRY          0x00000005
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_CLEAR_UC_TX_PORTS        0x00000006
#define PNIP_REG_FDBCOMMAND_IF_CONTROL__VAL_F_CODE_PTCP_CHANGE              0x00000007

// ---------- VLAN ---------------------------------
// -

// ---------- SYNC ---------------------------------
// register: PNIP_REG_SYNCCOMMAND_IF_CONTROL
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_CONFREQUEST_DISABLE            0x00000000
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_CONFREQUEST_ENABLE             0x00000001

#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_IF_SELECT_IFA                  0x00000001

#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_SELECT_APPL_TIMER_1            0x00000001
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_SELECT_APPL_TIMER_2            0x00000002
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_SELECT_APPL_TIMER_3            0x00000004

#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_CONFERROR_ERROR                0x00000001
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_CONFERROR_NO_ERROR             0x00000000

#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_NOP                     0x00000000
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_SYNC_A           0x00000001
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_SYNC_B           0x00000002
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_TIME             0x00000003
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_APPLCYCLE        0x00000004
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_COMCYCLE         0x00000005
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_BASECYCLE        0x00000006
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_SYNCCYCLE        0x00000007
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_UPDATE_SYNCTIME         0x00000008
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_STAMP                   0x00000009
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_CONNECT_FREE            0x0000000A
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_CONNECT_SYNC_A          0x0000000B
#define PNIP_REG_SYNCCOMMAND_IF_CONTROL__VAL_F_CODE_CONNECT_SYNC_B          0x0000000C


// ---------- PHY ---------------------------------
// register: PNIP_REG_PHY_CONTROL
// Non HERA_FPGA: To fullfill the ERTEC200+ internal PHY timing requirement a value of 0b10 (=2) has
//                to be configured for MDIO_HOLD. This value can always be configured.
//                See RQ "430081 Parametrierung von MDIO_hold im PN-IP Register "PHY_Control" auf 0b10"
// HERA-FPGA:     MDIO_HOLD has to be set to "7", to compensate for the delay of the level shifters. See RQ 1807069.
#define PNIP_REG_PHY_CONTROL_MDIO_HOLD_VAL_DEFAULT                          0x00000002
#define PNIP_REG_PHY_CONTROL_MDIO_HOLD_VAL_HERA_FPGA                        0x00000007

/**
@defgroup       IP_VERSION__CONFIGURATION CONFIGURATION
@ingroup        IP_VERSION
@brief          Configurations of the PN-IP:      0x0000: 4-Port PN-IP, 2IF (PN-IP completion)     0x0001: 4-Port PN-IP, 1IF -- FPGA-Validation     0x0002: 2-Port PN-IP, 1IF -- ERTEC200+
@param Address  0x00000000
@param Mask     0xFFFF0000
@param Shift    16
@param Access   r,
@param Version  -1
Version with PNIP_HAL_ET200PF0_... 
@param Type     ERTEC200P FPGA
@param Reset    0x00000002
Version with PNIP_HAL_ET200PA0_... 
@param Type     ERTEC200P ASIC
@param Reset    0x00000012
Version with PNIP_HAL_HERAF0I04_... 
@param Type     HERA FPGA Increment 4
@param Reset    0x00000004
*/
#define PNIP_HAL_REG_IP_VERSION__MSK_CONFIGURATION                  0xFFFF0000
#define PNIP_HAL_REG_IP_VERSION_SHFT_CONFIGURATION                  16
#define PNIP_HAL_ET200PF0_REG_IP_VERSION_RSTV_CONFIGURATION         0x00000002
#define PNIP_HAL_ET200PA0_REG_IP_VERSION_RSTV_CONFIGURATION         0x00000012
#define PNIP_HAL_HERAF0I04_REG_IP_VERSION_RSTV_CONFIGURATION        0x00000004
#define PNIP_HAL_HERAF0I08_REG_IP_VERSION_RSTV_CONFIGURATION        0x00000008



/*===========================================================================*/
/*                                 macros                                    */
/*===========================================================================*/

#if (   (PNIP_R2_RAM_VLAN_RAM_START != PNIP_R2F0_RAM_VLAN_RAM_START)                       \
      ||(PNIP_R2_RAM_VLAN_RAM_START != PNIP_R3F0P2_RAM_VLAN_RAM_START)                     \
      ||(PNIP_R2_RAM_VLAN_RAM_START != PNIP_R3F0P4_RAM_VLAN_RAM_START)                     \
      ||(PNIP_R2_RAM_VLAN_RAM_START != PNIP_R2A0_RAM_VLAN_RAM_START)                       \
      ||(PNIP_R2_RAM_VLAN_RAM_START != PNIP_R3A0P2_RAM_VLAN_RAM_START)                     \
      ||(PNIP_R2_RAM_VLAN_RAM_START != PNIP_R3A0P4_RAM_VLAN_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_VLAN_RAM_START are not equal to PNIP_R2_RAM_VLAN_RAM_START"
#endif

#if (   (PNIP_R1_RAM_QUEUECTRL_RAM_START != PNIP_R2P4_RAM_QUEUECTRL_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUECTRL_RAM_START != PNIP_R2P2_RAM_QUEUECTRL_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUECTRL_RAM_START != PNIP_R3P2_RAM_QUEUECTRL_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUECTRL_RAM_START != PNIP_R3P4_RAM_QUEUECTRL_RAM_START)   )
#error "one or more defines from group PNIP_xxxx_RAM_QUEUECTRL_RAM_START are not equal to PNIP_R1_RAM_QUEUECTRL_RAM_START"
#endif

#if (   (PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R2P4_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P2_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P4_RAM_FDB_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_FDB_RAM_START are not equal to PNIP_R2P2_RAM_FDB_RAM_START"
#endif

#if (   (PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R2P2_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R2P3_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R2P4_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R3P1_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R3P2_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R3P3_RAM_STATISTIC_RAM_START)                     \
      ||(PNIP_R2P1_RAM_STATISTIC_RAM_START != PNIP_R3P4_RAM_STATISTIC_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_STATISTIC_RAM_START are not equal to PNIP_R2P1_RAM_STATISTIC_RAM_START"
#endif

#if (   (PNIP_R3_RAM_PACKDATA_RAM_START != PNIP_R2P4_RAM_PACKDATA_RAM_START)                     \
      ||(PNIP_R3_RAM_PACKDATA_RAM_START != PNIP_R2P2_RAM_PACKDATA_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_PACKDATA_RAM_START are not equal to PNIP_R3_RAM_PACKDATA_RAM_START"
#endif

#if (   (PNIP_R1_RAM_QUEUEDATA_RAM_START != PNIP_R2P4_RAM_QUEUEDATA_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUEDATA_RAM_START != PNIP_R2P2_RAM_QUEUEDATA_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUEDATA_RAM_START != PNIP_R3P4_RAM_QUEUEDATA_RAM_START)                     \
      ||(PNIP_R1_RAM_QUEUEDATA_RAM_START != PNIP_R3P2_RAM_QUEUEDATA_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_QUEUEDATA_RAM_START are not equal to PNIP_R1_RAM_QUEUEDATA_RAM_START"
#endif

#if (   (PNIP_R2P2_RAM_SYNC_RAM_START != PNIP_R2P4_RAM_SYNC_RAM_START)                     \
      ||(PNIP_R2P2_RAM_SYNC_RAM_START != PNIP_R3P2_RAM_SYNC_RAM_START)                     \
      ||(PNIP_R2P2_RAM_SYNC_RAM_START != PNIP_R3P4_RAM_SYNC_RAM_START)    )
#error "one or more defines from group PNIP_R2P2_RAM_SYNC_RAM_START are not equal to PNIP_R2P2_RAM_SYNC_RAM_START"
#endif

#if (   (PNIP_R2P2_RAM_CMDCTRL_RAM_START != PNIP_R2P4_RAM_CMDCTRL_RAM_START)                     \
      ||(PNIP_R2P2_RAM_CMDCTRL_RAM_START != PNIP_R3P2_RAM_CMDCTRL_RAM_START)                     \
      ||(PNIP_R2P2_RAM_CMDCTRL_RAM_START != PNIP_R3P4_RAM_CMDCTRL_RAM_START)    )
#error "one or more defines from group PNIP_R2P2_RAM_CMDCTRL_RAM_START are not equal to PNIP_R2P2_RAM_CMDCTRL_RAM_START"
#endif

#if (   (PNIP_R2P4_RAM_APICTRL_RAM_START != PNIP_R2P2_RAM_APICTRL_RAM_START)                     \
      ||(PNIP_R2P4_RAM_APICTRL_RAM_START != PNIP_R3P4_RAM_APICTRL_RAM_START)                     \
      ||(PNIP_R2P4_RAM_APICTRL_RAM_START != PNIP_R3P2_RAM_APICTRL_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_APICTRL_RAM_START are not equal to PNIP_R2P4_RAM_APICTRL_RAM_START"
#endif

#if (   (PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R2P4_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P2_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P4_RAM_FDB_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_FDB_RAM_START are not equal to PNIP_R2P2_RAM_FDB_RAM_START"
#endif

#if (   (PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R2P4_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P2_RAM_FDB_RAM_START)                     \
      ||(PNIP_R2P2_RAM_FDB_RAM_START != PNIP_R3P4_RAM_FDB_RAM_START)    )
#error "one or more defines from group PNIP_xxxx_RAM_FDB_RAM_START are not equal to PNIP_R2P2_RAM_FDB_RAM_START"
#endif

/* macro pairs */
#if (PNIP_R3F0P2_RAM_VLAN_RAM_LEN != PNIP_R3F0P4_RAM_VLAN_RAM_LEN)                     
#error "PNIP_R3F0P2_RAM_VLAN_RAM_LEN are not equal to PNIP_R3F0P4_RAM_VLAN_RAM_LEN"
#endif

#if (PNIP_A0_REG_IP_DEVELOPMENT__MSK_TYPE != PNIP_F0_REG_IP_DEVELOPMENT__MSK_TYPE)                     
#error "PNIP_A0_REG_IP_DEVELOPMENT__MSK_TYPE are not equal to PNIP_F0_REG_IP_DEVELOPMENT__MSK_TYPE"
#endif

#if (PNIP_A0_REG_IP_DEVELOPMENT__MSK_TYPE != PNIP_F0_REG_IP_DEVELOPMENT__MSK_TYPE)                     
#error "PNIP_A0_REG_IP_DEVELOPMENT_SHFT_TYPE are not equal to PNIP_F0_REG_IP_DEVELOPMENT_SHFT_TYPE"
#endif

#if (PNIP_R2F0_REG_PPM_FSO_LEADTIME != PNIP_R2A0_REG_PPM_FSO_LEADTIME)                     
#error "PNIP_R2F0_REG_PPM_FSO_LEADTIME are not equal to PNIP_R2A0_REG_PPM_FSO_LEADTIME"
#endif

#if (   (PNIP_R1_REG_IP_VERSION__MSK_VERSION != PNIP_R2_REG_IP_VERSION__MSK_VERSION)                     \
      ||(PNIP_R1_REG_IP_VERSION__MSK_VERSION != PNIP_R3_REG_IP_VERSION__MSK_VERSION)    )
#error "PNIP_R1_REG_IP_VERSION__MSK_VERSION are not equal to PNIP_R2_REG_IP_VERSION__MSK_VERSION or to PNIP_R3_REG_IP_VERSION__MSK_VERSION"
#endif

#if (   (PNIP_R1_REG_IP_VERSION_SHFT_VERSION != PNIP_R2_REG_IP_VERSION_SHFT_VERSION)                     \
      ||(PNIP_R1_REG_IP_VERSION_SHFT_VERSION != PNIP_R3_REG_IP_VERSION_SHFT_VERSION)    )
#error "PNIP_R1_REG_IP_VERSION__MSK_VERSION are not equal to PNIP_R2_REG_IP_VERSION__MSK_VERSION or to PNIP_R3_REG_IP_VERSION__MSK_VERSION"
#endif

#if (PNIP_A0_REG_IP_DEVELOPMENT__MSK_TYPE != PNIP_F0_REG_IP_DEVELOPMENT__MSK_TYPE)                   
#error "PNIP_A0_REG_IP_DEVELOPMENT__MSK_TYPE are not equal to PNIP_F0_REG_IP_DEVELOPMENT__MSK_TYPE"
#endif

#if (PNIP_A0_REG_IP_DEVELOPMENT_SHFT_TYPE != PNIP_F0_REG_IP_DEVELOPMENT_SHFT_TYPE)                   
#error "PNIP_A0_REG_IP_DEVELOPMENT_SHFT_TYPE are not equal to PNIP_F0_REG_IP_DEVELOPMENT_SHFT_TYPE"
#endif

#if (PNIP_R2_REG_SYNCCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE != PNIP_R3_REG_SYNCCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE)                   
#error "PNIP_R2_REG_SYNCCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE are not equal to PNIP_R3_REG_SYNCCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_USER_ID != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_USER_ID)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_USER_ID are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_USER_ID"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_CONFREQUEST != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_CONFREQUEST)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_CONFREQUEST are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_CONFREQUEST"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_IF_SELECT != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_IF_SELECT)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_IF_SELECT are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_IF_SELECT"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_F_CODE != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_F_CODE)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_F_CODE are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_F_CODE"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL"
#endif

#if (PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE != PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE)                   
#error "PNIP_R2_REG_PPMCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE are not equal to PNIP_R3_REG_PPMCOMMAND_IF_CONTROL_SHFT_COMMANDVALUE"
#endif

#if (PNIP_R2_REG_PPMERRSTATUS != PNIP_R3_REG_PPMERRSTATUS)                   
#error "PNIP_R2_REG_PPMERRSTATUS are not equal to PNIP_R3_REG_PPMERRSTATUS"
#endif

#if (PNIP_R2_REG_ACCESS_ERROR != PNIP_R3_REG_ACCESS_ERROR)                   
#error "PNIP_R2_REG_ACCESS_ERROR are not equal to PNIP_R3_REG_ACCESS_ERROR"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_00 != PNIP_R3_REG_FILTERCODEBASE_IFA_00)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_00 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_00"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_01 != PNIP_R3_REG_FILTERCODEBASE_IFA_01)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_01 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_01"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_02 != PNIP_R3_REG_FILTERCODEBASE_IFA_02)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_02 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_02"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_03 != PNIP_R3_REG_FILTERCODEBASE_IFA_03)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_03 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_03"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_04 != PNIP_R3_REG_FILTERCODEBASE_IFA_04)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_04 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_04"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_05 != PNIP_R3_REG_FILTERCODEBASE_IFA_05)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_05 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_05"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_06 != PNIP_R3_REG_FILTERCODEBASE_IFA_06)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_06 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_06"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_07 != PNIP_R3_REG_FILTERCODEBASE_IFA_07)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_07 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_07"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_08 != PNIP_R3_REG_FILTERCODEBASE_IFA_08)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_08 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_08"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_09 != PNIP_R3_REG_FILTERCODEBASE_IFA_09)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_09 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_09"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_10 != PNIP_R3_REG_FILTERCODEBASE_IFA_10)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_10 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_10"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_11 != PNIP_R3_REG_FILTERCODEBASE_IFA_11)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_11 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_11"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_12 != PNIP_R3_REG_FILTERCODEBASE_IFA_12)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_12 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_12"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_13 != PNIP_R3_REG_FILTERCODEBASE_IFA_13)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_13 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_13"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_14 != PNIP_R3_REG_FILTERCODEBASE_IFA_14)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_14 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_14"
#endif

#if (PNIP_R2_REG_FILTERCODEBASE_IFA_15 != PNIP_R3_REG_FILTERCODEBASE_IFA_15)                   
#error "PNIP_R2_REG_FILTERCODEBASE_IFA_15 are not equal to PNIP_R3_REG_FILTERCODEBASE_IFA_15"
#endif

#if (PNIP_R2_REG_SNDTABLEBASE_IFA != PNIP_R3_REG_SNDTABLEBASE_IFA)                   
#error "PNIP_R2_REG_SNDTABLEBASE_IFA are not equal to PNIP_R3_REG_SNDTABLEBASE_IFA"
#endif

#if (PNIP_R2_REG_RCVTABLEBASE_IFA != PNIP_R3_REG_RCVTABLEBASE_IFA)                   
#error "PNIP_R2_REG_RCVTABLEBASE_IFA are not equal to PNIP_R3_REG_RCVTABLEBASE_IFA"
#endif

#if (PNIP_R2_REG_SDTABLEBASE_IFA != PNIP_R3_REG_SDTABLEBASE_IFA)                   
#error "PNIP_R2_REG_SDTABLEBASE_IFA are not equal to PNIP_R3_REG_SDTABLEBASE_IFA"
#endif

#if (PNIP_R2_REG_STORETABLEBASE_IFA != PNIP_R3_REG_STORETABLEBASE_IFA)                   
#error "PNIP_R2_REG_STORETABLEBASE_IFA are not equal to PNIP_R3_REG_STORETABLEBASE_IFA"
#endif

#if (    (PNIP_R2A0_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH != PNIP_R2F0_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH)    \
       ||(PNIP_R2A0_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH != PNIP_R3_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH)  )
#error "PNIP_A0_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH are not equal to PNIP_R2F0_REG_IRQ2_CONTROL__MSK_IRQ_LENGTH"
#endif

#if (    (PNIP_R2A0_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH != PNIP_R2F0_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH)      \
       ||(PNIP_R2A0_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH != PNIP_R3_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH)  )
#error "PNIP_A0_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH are not equal to PNIP_R2F0_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH"
#endif

#if (    (PNIP_R2A0_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH != PNIP_R2F0_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH)  \
       ||(PNIP_R2A0_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH != PNIP_R3_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH) )
#error "PNIP_R2F0_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH and PNIP_R2A0_REG_IRQ3_CONTROL__MSK_IRQ_LENGTH and PNIP_R3_REG_IRQ2_CONTROL_SHFT_IRQ_LENGTH are not equal"
#endif

#if (    (PNIP_R2A0_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH != PNIP_R2F0_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH)  \
       ||(PNIP_R2A0_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH != PNIP_R3_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH) )
#error "PNIP_R2A0_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH and PNIP_R2F0_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH and PNIP_R3_REG_IRQ3_CONTROL_SHFT_IRQ_LENGTH are not equal"
#endif

#if (PNIP_R2_REG_DROPCOUNT_IFA_00 != PNIP_R3_REG_DROPCOUNT_IFA_00)                   
#error "PNIP_R2_REG_DROPCOUNT_IFA_00 are not equal to PNIP_R3_REG_DROPCOUNT_IFA_00"
#endif


#if (PNIP_R2_REG_DROPCOUNT_IFA_01 != PNIP_R3_REG_DROPCOUNT_IFA_01)                   
#error "PNIP_R2_REG_DROPCOUNT_IFA_01 are not equal to PNIP_R3_REG_DROPCOUNT_IFA_01"
#endif

#if (    (PNIP_R2A0_REG_UC_LFSR_RANGE_A != PNIP_R2F0_REG_UC_LFSR_RANGE_A)            \
       ||(PNIP_R2A0_REG_UC_LFSR_RANGE_A != PNIP_R3P2_REG_UC_LFSR_RANGE_A)            \
       ||(PNIP_R2A0_REG_UC_LFSR_RANGE_A != PNIP_R3P4_REG_UC_LFSR_RANGE_A) ) 
#error "PNIP_R2A0_REG_UC_LFSR_RANGE_A, PNIP_R2F0_REG_UC_LFSR_RANGE_A,  PNIP_R3P2_REG_UC_LFSR_RANGE_A and PNIP_R3P4_REG_UC_LFSR_RANGE_A are not equal"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_FETCHTIMEDELTA_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_FETCHTIMEDELTA_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_FETCHTIMEDELTA_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_FETCHTIMEDELTA_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_FETCHTIMEDELTA_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_FETCHTIMEDELTA_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_FETCHTIMEDELTA_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_FETCHTIMEDELTA_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_OUTSTANDREADS_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_OUTSTANDREADS_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_OUTSTANDREADS_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_PPM_OUTSTANDREADS_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_OUTSTANDREADS_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_OUTSTANDREADS_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_OUTSTANDREADS_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_PPM_OUTSTANDREADS_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_PPM_OUTSTANDREADS_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_PPM_OUTSTANDREADS_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_PPM_OUTSTANDREADS_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_PPM_OUTSTANDREADS_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_RTC3_FSO_MODE_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_RTC3_FSO_MODE_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_RTC3_FSO_MODE_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM__MSK_RTC3_FSO_MODE_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_RTC3_FSO_MODE_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_RTC3_FSO_MODE_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_RTC3_FSO_MODE_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_SHFT_RTC3_FSO_MODE_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_RTC3_FSO_MODE_FASTMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_RTC3_FSO_MODE_FASTMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_RTC3_FSO_MODE_FASTMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_FASTMEM_RSTV_RTC3_FSO_MODE_FASTMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_FETCHTIMEDELTA_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_FETCHTIMEDELTA_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_FETCHTIMEDELTA_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_FETCHTIMEDELTA_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_FETCHTIMEDELTA_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_FETCHTIMEDELTA_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_FETCHTIMEDELTA_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_FETCHTIMEDELTA_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_OUTSTANDREADS_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_OUTSTANDREADS_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_OUTSTANDREADS_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_PPM_OUTSTANDREADS_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_OUTSTANDREADS_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_OUTSTANDREADS_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_OUTSTANDREADS_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_PPM_OUTSTANDREADS_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_PPM_OUTSTANDREADS_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_PPM_OUTSTANDREADS_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_PPM_OUTSTANDREADS_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_PPM_OUTSTANDREADS_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_RTC3_FSO_MODE_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_RTC3_FSO_MODE_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_RTC3_FSO_MODE_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM__MSK_RTC3_FSO_MODE_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_RTC3_FSO_MODE_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_RTC3_FSO_MODE_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_RTC3_FSO_MODE_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_SHFT_RTC3_FSO_MODE_SLOWMEM"
#endif

#if (PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_RTC3_FSO_MODE_SLOWMEM != PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_RTC3_FSO_MODE_SLOWMEM)
#error "PNIP_R3A0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_RTC3_FSO_MODE_SLOWMEM are not equal to PNIP_R3F0_REG_PPM_FETCHTIMEDELTA_SLOWMEM_RSTV_RTC3_FSO_MODE_SLOWMEM"
#endif

#if (PNIP_R3P2_RAM_APICTRL_RAM_START != PNIP_R3P4_RAM_APICTRL_RAM_START)
#error "PNIP_R3P2_RAM_APICTRL_RAM_START are not equal to PNIP_R3P4_RAM_APICTRL_RAM_START"
#endif

#if (PNIP_R3P2_RAM_APINRTCTRL_RAM_START != PNIP_R3P4_RAM_APINRTCTRL_RAM_START)
#error "PNIP_R3P2_RAM_APINRTCTRL_RAM_START are not equal to PNIP_R3P4_RAM_APINRTCTRL_RAM_START"
#endif

#if (   (PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P2_SHFT_ACW_TLISTPTR) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P3_SHFT_ACW_TLISTPTR) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P4_SHFT_ACW_TLISTPTR) )
#error "PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_ACW_TLISTPTR are not equal to PNIP_R3_REG_ACW_TLISTPTR_CYCM_PX_SHFT_ACW_TLISTPTR"
#endif
    
#if (   (PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P2_SHFT_ACW_TLISTPTR) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P3_SHFT_ACW_TLISTPTR) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_ACW_TLISTPTR != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P4_SHFT_ACW_TLISTPTR) )
#error "PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_ACW_TLISTPTR are not equal to PNIP_R3_REG_ACW_TLISTPTR_CYCN_PX_SHFT_ACW_TLISTPTR"
#endif
    
#if (   (PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P2_SHFT_MAX_ENTRIES) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P3_SHFT_MAX_ENTRIES) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCM_P4_SHFT_MAX_ENTRIES) )
#error "PNIP_R3_REG_ACW_TLISTPTR_CYCM_P1_SHFT_MAX_ENTRIES are not equal to PNIP_R3_REG_ACW_TLISTPTR_CYCM_PX_SHFT_MAX_ENTRIES"
#endif
    
#if (   (PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P2_SHFT_MAX_ENTRIES) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P3_SHFT_MAX_ENTRIES) \
      ||(PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_MAX_ENTRIES != PNIP_R3_REG_ACW_TLISTPTR_CYCN_P4_SHFT_MAX_ENTRIES) )
#error "PNIP_R3_REG_ACW_TLISTPTR_CYCN_P1_SHFT_MAX_ENTRIES are not equal to PNIP_R3_REG_ACW_TLISTPTR_CYCN_PX_SHFT_MAX_ENTRIES"
#endif

#if (   (PNIP_REG_DMACW_COUNT_0_IFA__MSK_ENABLECOUNT != PNIP_REG_DMACW_COUNT_1_IFA__MSK_ENABLECOUNT) \
      ||(PNIP_REG_DMACW_COUNT_0_IFA__MSK_ENABLECOUNT != PNIP_REG_DMACW_COUNT_2_IFA__MSK_ENABLECOUNT) \
      ||(PNIP_REG_DMACW_COUNT_0_IFA__MSK_ENABLECOUNT != PNIP_REG_DMACW_COUNT_3_IFA__MSK_ENABLECOUNT) )
#error "PNIP_REG_DMACW_COUNT_0_IFA__MSK_ENABLECOUNT are not equal to PNIP_REG_DMACW_COUNT_X_IFA__MSK_ENABLECOUNT"
#endif
    
#if (   (PNIP_R2_REG_DMACW_COUNT_0_IFA__MSK_ENABLEPRIORITY != PNIP_R2_REG_DMACW_COUNT_1_IFA__MSK_ENABLEPRIORITY) \
      ||(PNIP_R2_REG_DMACW_COUNT_0_IFA__MSK_ENABLEPRIORITY != PNIP_R2_REG_DMACW_COUNT_2_IFA__MSK_ENABLEPRIORITY) \
      ||(PNIP_R2_REG_DMACW_COUNT_0_IFA__MSK_ENABLEPRIORITY != PNIP_R2_REG_DMACW_COUNT_3_IFA__MSK_ENABLEPRIORITY) )
#error "PNIP_REG_DMACW_COUNT_0_IFA__MSK_ENABLEPRIORITY are not equal to PNIP_REG_DMACW_COUNT_X_IFA__MSK_ENABLEPRIORITY"
#endif
    
#if (   (PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_INCLUDEPADDING != PNIP_R3_REG_DMACW_COUNT_1_IFA__MSK_INCLUDEPADDING) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_INCLUDEPADDING != PNIP_R3_REG_DMACW_COUNT_2_IFA__MSK_INCLUDEPADDING) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_INCLUDEPADDING != PNIP_R3_REG_DMACW_COUNT_3_IFA__MSK_INCLUDEPADDING) )
#error "PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_INCLUDEPADDING are not equal to PNIP_R3_REG_DMACW_COUNT_X_IFA__MSK_INCLUDEPADDING"
#endif    

#if (   (PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_1_IFA__MSK_ADDOVERHEAD) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_2_IFA__MSK_ADDOVERHEAD) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_3_IFA__MSK_ADDOVERHEAD) )
#error "PNIP_R3_REG_DMACW_COUNT_0_IFA__MSK_ADDOVERHEAD are not equal to PNIP_R3_REG_DMACW_COUNT_X_IFA__MSK_ADDOVERHEAD"
#endif

#if (   (PNIP_R3_REG_DMACW_COUNT_0_IFA_SHFT_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_1_IFA_SHFT_ADDOVERHEAD) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA_SHFT_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_2_IFA_SHFT_ADDOVERHEAD) \
      ||(PNIP_R3_REG_DMACW_COUNT_0_IFA_SHFT_ADDOVERHEAD != PNIP_R3_REG_DMACW_COUNT_3_IFA_SHFT_ADDOVERHEAD) )
#error "PNIP_R3_REG_DMACW_COUNT_0_IFA_SHFT_ADDOVERHEAD are not equal to PNIP_R3_REG_DMACW_COUNT_X_IFA_SHFT_ADDOVERHEAD"
#endif
    
    
    
/*****************************************************************************/
/*  end of file eddp_hal_pnip_val.h                                          */
/*****************************************************************************/

#ifdef __cplusplus  /* If C++ - compiler: End of C linkage */
}
#endif

/*---------------------------------------------------------------------------*/
#endif  // of EDDP_HAL_PNIP_VAL_H

